- defaults:
    link:
      relink: true

- clean: ['$HOME']

- link:
    ~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/: windows_terminal/settings.json

- shell:
  - [git submodule update --init --recursive, Installing submodules]