#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

## Cleaning Default Trash
sudo apt update -y && sudo apt upgrade -y
# sudo apt purge gnome-2048 aisleriot atomix gnome-chess five-or-more hitori iagno gnome-klotski lightsoff gnome-mahjongg gnome-mines gnome-nibbles quadrapassel four-in-a-row gnome-robots gnome-sudoku swell-foop tali gnome-taquin gnome-tetravex -y 

## Installing Fira Code
sudo add-apt-repository universe -y
sudo apt install fonts-firacode -y

## Installing Rofi
sudo apt install rofi -y

# Installing Zsh
sudo apt install zsh -y

# Disable Hybernate and Suspend
sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

sudo apt autoremove -y

if [ -d ~/.oh-my-zsh ]; then

    sudo apt autoremove

    cd "${BASEDIR}"
    git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
    git submodule update --init --recursive "${DOTBOT_DIR}"

    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
else
    echo ERROR: Oh-my-zsh needs to be installed. run: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    exit 1 # terminate and indicate error
fi