" install vim-plug if necessary
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'airblade/vim-gitgutter'
Plug 'drewtempelmeyer/palenight.vim'

call plug#end()

" show lightline
set laststatus=2

" toggle nerdtree
map <C-o> :NERDTreeToggle<CR>

" use palenight 
set background=dark
colorscheme palenight
let g:lightline = {
      \ 'colorscheme': 'palenight',
      \ }
let g:palenight_terminal_italics=1
if (has("termguicolors"))
  set termguicolors
endif

" disable backups
:set nobackup
