# ~/.zshrc

export ZPLUG_HOME=${HOME}/.zplug
# install zplug if not yet installed
if [[ ! -d ~/.zplug ]]; then
    git clone https://github.com/zplug/zplug ~/.zplug
    source ~/.zplug/init.zsh && zplug update --self
fi

source ~/.zplug/init.zsh

zplug "denysdovhan/spaceship-prompt", as:theme
zplug "chrissicool/zsh-256color"
zplug "seebi/dircolors-solarized"

export NVM_LAZY_LOAD=true
zplug "lukechilds/zsh-nvm"

zplug "voronkovich/gitignore.plugin.zsh"
zplug "plugins/git", from:oh-my-zsh

zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2

if ! zplug check; then
    zplug install
fi

zplug load

# load dircolors
eval $(dircolors ${ZPLUG_HOME}/repos/seebi/dircolors-solarized/dircolors.256dark)

## history file configuration
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000

## History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt inc_append_history     # add commands to HISTFILE in order of execution
setopt share_history # share command history data

# dircolors
alias ls='ls --color=auto'
if [ -f "$HOME/.dircolors" ]; then
    eval `dircolors -b "$HOME/.dircolors"`
else
    if [ -f "/etc/dircolors" ]; then
    eval `dircolors -b "/etc/dircolors"`
    fi
fi

# List directory contents
alias lsa='ls -lah'
alias l='ls -lah'
alias ll='ls -lh'
alias la='ls -lAh'

# check weather
weather() {
    city="$1"

    if [ -z "$city" ]; then
        city="Hannover,Germany"
    fi

    eval "curl http://wttr.in/${city}"
}

# reload configurations
alias reload="exec ${SHELL} -l"
