# ~/.zshrc

umask 022

# install zplug if not yet installed
if [[ ! -d ${ZDOTDIR:-~}/.antidote ]]; then
    git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-~}/.antidote
fi

source ${ZDOTDIR:-~}/.antidote/antidote.zsh

autoload -Uz compinit && compinit

antidote load

## history file configuration
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000
# fix delete key
bindkey "^[[3~" delete-char
bindkey "^[3;5~" delete-char

## History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt inc_append_history     # add commands to HISTFILE in order of execution
setopt share_history          # share command history data

# FZF CONFIGURATION
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND="fd . --maxdepth 1"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_COMPLETION_TRIGGER='~~'
export FZF_DEFAULT_OPTS='--multi --height=80%  --layout=reverse-list --border=double --info=inline --pointer='→''

## ALL Aliases
## FZF
alias pf="fd . --maxdepth 1 --type f | fzf --multi --height=80% --border=sharp  --preview='bat --color=always --style=numbers {}' --preview-window='45%,border-sharp' --bind shift-up:preview-page-up,shift-down:preview-page-down"
alias pd="fd . --maxdepth 1 --type d | fzf --multi --height=80% --border=sharp --preview='tree -C {}' --preview-window='45%,border-sharp' --bind shift-up:preview-page-up,shift-down:preview-page-down"
# reload
alias reload="source ~/.zshrc"
# List directory contents
alias ls='ls --color=auto'
alias lsa='ls -lah'
alias l='ls -lah'
alias ll='ls -lh'
alias la='ls -lAh'
## Brew
alias update='brew update; brew upgrade'
# check weather
weather() {
    city="$1"

    if [ -z "$city" ]; then
        city="Hannover,Germany"
    fi

    eval "curl http://wttr.in/${city}"
}
# reload configurations
alias reload="source ~/.zshrc"

eval "$(starship init zsh)"
eval "$(zoxide init --cmd cd zsh)"
